name: Create PR on Issue Open

on:
  issues:
    types: [opened]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create branch and add commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Fetch the latest changes
          git fetch origin
          
          branch_name="issue-${GITHUB_EVENT_ISSUE_NUMBER}"
          
          # Check if the branch already exists
          if git ls-remote --exit-code --heads origin $branch_name; then
            # If it exists, delete it (both locally and remotely)
            git push origin --delete $branch_name || true
            git branch -D $branch_name || true
          fi
          
          # Create and checkout the new branch
          git checkout -b $branch_name
          
          # Create a dummy file or modify an existing file
          echo "This file is created in response to Issue #${GITHUB_EVENT_ISSUE_NUMBER}" > issue_${GITHUB_EVENT_ISSUE_NUMBER}.txt
          
          git add issue_${GITHUB_EVENT_ISSUE_NUMBER}.txt
          git commit -m "Initialize branch for Issue #${GITHUB_EVENT_ISSUE_NUMBER}"
          
          # Force push the branch
          git push -f origin $branch_name

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head "issue-${GITHUB_EVENT_ISSUE_NUMBER}" \
            --title "Address Issue #${GITHUB_EVENT_ISSUE_NUMBER}" \
            --body "This PR is created in response to Issue #${GITHUB_EVENT_ISSUE_NUMBER}. Please review and update as necessary."
